[package]
name = "otus-iced"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = {  version = "0.13" }
regex = { version = "1.11.1" }

[[bin]]
name = "server"
path = "src/main.rs"

[[example]]
name = "cli_termometer"

[[example]]
name = "cli_socket"
