[package]
name = "otus-iced"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio ={ version = "*" }
iced = {  version = "0.13", features = [ "tokio"] }
regex = { version = "1.11.1" }

[[bin]]
name = "server"
path = "src/main.rs"

[[example]]
name = "cli_termo"

[[example]]
name = "cli_socket"
